package org.wl.core.security.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.wl.core.dao.sqlmapper.SqlMapper;
import org.wl.core.security.domain.WlResource;
import org.wl.core.security.domain.WlResourceExample;

public interface WlResourceMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int countByExample(WlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int deleteByExample(WlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int deleteByPrimaryKey(Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int insert(WlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int insertSelective(WlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlResource> selectByExampleWithRowbounds(WlResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlResource> selectByExample(WlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    WlResource selectByPrimaryKey(Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByExampleSelective(@Param("record") WlResource record, @Param("example") WlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByExample(@Param("record") WlResource record, @Param("example") WlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByPrimaryKeySelective(WlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByPrimaryKey(WlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int countByModel(WlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlResource> selectByModel(WlResource model);
}