package org.wl.core.security.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.wl.core.dao.sqlmapper.SqlMapper;
import org.wl.core.security.domain.WlRole;
import org.wl.core.security.domain.WlRoleExample;

public interface WlRoleMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int countByExample(WlRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int deleteByExample(WlRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int insert(WlRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int insertSelective(WlRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlRole> selectByExampleWithBLOBsWithRowbounds(WlRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlRole> selectByExampleWithBLOBs(WlRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlRole> selectByExampleWithRowbounds(WlRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlRole> selectByExample(WlRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    WlRole selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByExampleSelective(@Param("record") WlRole record, @Param("example") WlRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") WlRole record, @Param("example") WlRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByExample(@Param("record") WlRole record, @Param("example") WlRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByPrimaryKeySelective(WlRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(WlRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int updateByPrimaryKey(WlRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    int countByModel(WlRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlRole> selectByModelWithBLOBs(WlRole model);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    List<WlRole> selectByModel(WlRole model);
}