package org.wl.core.security.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.wl.core.dao.sqlmapper.SqlMapper;
import org.wl.core.security.domain.WlUserRoleExample;
import org.wl.core.security.domain.WlUserRoleKey;

public interface WlUserRoleMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int countByExample(WlUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int deleteByExample(WlUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int deleteByPrimaryKey(WlUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int insert(WlUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int insertSelective(WlUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    List<WlUserRoleKey> selectByExampleWithRowbounds(WlUserRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    List<WlUserRoleKey> selectByExample(WlUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int updateByExampleSelective(@Param("record") WlUserRoleKey record, @Param("example") WlUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int updateByExample(@Param("record") WlUserRoleKey record, @Param("example") WlUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    int countByModel(WlUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    List<WlUserRoleKey> selectByModel(WlUserRoleKey model);
}