package org.wl.core.security.service;

import java.util.List;

import org.wl.core.security.domain.WlUser;
import org.wl.core.security.domain.WlUserExample;

/**
 * sys_user Service
 * 
 * @author alpha zhang
 */
public interface WlUserService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int countByExample(WlUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int deleteByExample(WlUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int insert(WlUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int insertSelective(WlUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    List<WlUser> selectByExample(WlUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    WlUser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int updateByExampleSelective(WlUser record, WlUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int updateByExample(WlUser record, WlUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int updateByPrimaryKeySelective(WlUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sun Dec 02 17:24:38 CST 2012
     */
    int updateByPrimaryKey(WlUser record);
	
}
