package org.wl.core.security.domain;

public class WlResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resourceid
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.code
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.url
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.type
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.priority
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.memo
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resourceid
     *
     * @return the value of sys_resource.resourceid
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resourceid
     *
     * @param resourceid the value for sys_resource.resourceid
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.code
     *
     * @return the value of sys_resource.code
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.code
     *
     * @param code the value for sys_resource.code
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.url
     *
     * @return the value of sys_resource.url
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.url
     *
     * @param url the value for sys_resource.url
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.priority
     *
     * @return the value of sys_resource.priority
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.priority
     *
     * @param priority the value for sys_resource.priority
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.memo
     *
     * @return the value of sys_resource.memo
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.memo
     *
     * @param memo the value for sys_resource.memo
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WlResource other = (WlResource) that;
        return (this.getResourceid() == null ? other.getResourceid() == null : this.getResourceid().equals(other.getResourceid()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getResourceid() == null) ? 0 : getResourceid().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Thu Jan 03 18:39:28 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceid=").append(resourceid);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", type=").append(type);
        sb.append(", priority=").append(priority);
        sb.append(", memo=").append(memo);
        sb.append("]");
        return sb.toString();
    }
}