package org.wl.core.security.domain;

public class WlRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleid
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.name
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.enable
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.blobtest
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    private byte[] blobtest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleid
     *
     * @return the value of sys_role.roleid
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleid
     *
     * @param roleid the value for sys_role.roleid
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.name
     *
     * @return the value of sys_role.name
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.name
     *
     * @param name the value for sys_role.name
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.enable
     *
     * @return the value of sys_role.enable
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.enable
     *
     * @param enable the value for sys_role.enable
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.blobtest
     *
     * @return the value of sys_role.blobtest
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public byte[] getBlobtest() {
        return blobtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.blobtest
     *
     * @param blobtest the value for sys_role.blobtest
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    public void setBlobtest(byte[] blobtest) {
        this.blobtest = blobtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WlRole other = (WlRole) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getBlobtest() == null ? other.getBlobtest() == null : this.getBlobtest().equals(other.getBlobtest()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getBlobtest() == null) ? 0 : getBlobtest().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Jan 03 16:30:12 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", name=").append(name);
        sb.append(", enable=").append(enable);
        sb.append(", blobtest=").append(blobtest);
        sb.append("]");
        return sb.toString();
    }
}